### PR TITLE
Add terms modal

### PR DESCRIPTION
**Pull request by bitsforpeace**
### What does this PR do?

Add terms modal

### CODE REVIEW

**Comment by codewiththeflowxyz** [comment]
One thing I noticed is that even when in the header says "Connect Wallet" and it shows me the terms modal, I can interact normally with the widgets (after closing the modal without accepting the terms). I guess this is because for wagmi we're still connected as I was connected before in localhost.

**Comment by codewiththeflowxyz** [comment]
When I try with a longer text the modal doesn't adapt to it and it looks like it needs more width.

image

**Review by codewiththeflowxyz — APPROVED** [review]
LGTM, but I noticed 2 issues. I commented them on the PR.

**Comment by bitsforpeace** [comment]
> When I try with a longer text the modal doesn't adapt to it and it looks like it needs more width.
> 
> image

Good thought. We can adjust once we get the design and text.

**Comment by bitsforpeace** [comment]
> One thing I noticed is that even when in the header says "Connect Wallet" and it shows me the terms modal, I can interact normally with the widgets (after closing the modal without accepting the terms). I guess this is because for wagmi we're still connected as I was connected before in localhost.
> 
> UPDATE: After disconnecting via MetaMask everything worked as expected. If you want to replicate this: after accepting the terms and connect your wallet, set `acceptedTerms` as false in localstorage. Then go back to the webapp.
> 
> image

Hmm, have to think about the best way to handle this. I don't think it'd actually be a problem on a deployed instance because the users wouldn't auto-connect the first time they visit the site. That is only happening since you've used the app previous to this code change. But maybe there's a way to enforce acceptance even in that case.

**Comment by generatorpoint** [comment]
I was able to replicate the connect wallet bug in a slightly different way: 
- make sure MM is disconnected from the site.
- open it incognito
- navigate to the account page and click connect
- note the header doesn't connect

It might just be a matter of adding the custom connect modal to the account page?

**Comment by bitsforpeace** [comment]
> I was able to replicate the connect wallet bug in a slightly different way:
> 
> * make sure MM is disconnected from the site.
> * open it incognito
> * navigate to the account page and click connect
> * note the header doesn't connect
> 
> It might just be a matter of adding the custom connect modal to the account page?

Good catch. The account page is still using the `ConnectButton` directly from rainbow. I will update it.

**Review by iceanddust — APPROVED** [review]

**Pull request merged**
