### PR TITLE
prevent inputting too many decimals

### PR DESCRIPTION
**Pull request by inclinedmind**

### CODE REVIEW

**Review by torhector2 — APPROVED** [review]

**Review by bitsforpeace — COMMENTED** [review]
We still have a visual issue where the cursor and numbers go behind the token image. Ideally, I think the input would end before the image and start auto-scrolling right as the user continued typing. What do others think?

Screenshot 2023-07-12 at 9 16 02 AM

**Comment by generatorpoint** [comment]
> We still have a visual issue where the cursor and numbers go behind the token image. Ideally, I think the input would end before the image and start auto-scrolling right as the user continued typing. What do others think?
> 
> Screenshot 2023-07-12 at 9 16 02 AM

yeah I noticed this in my branch too, I wonder if it can be accomplished without scrolling by reducing the padding inside the input? or the padding of the card? We can cross references the designs in dev mode to see what values Tiago used for the spacing

**Comment by generatorpoint** [comment]
Actually I just looked at what uniswap does and they do the scrolling thing that Adam mentioned. Maybe that is the way

input focused:
Screenshot 2023-07-12 at 12 40 16 PM

input not focused:
Screenshot 2023-07-12 at 12 40 47 PM

**Comment by generatorpoint** [comment]
> I just checked and the overflowing can be fixed by adding a padding-right to the token input, as for the unfocused state, maybe that can be accomplished with the number formatting in the input?

The unfocused state probably isn't as critical, so don't worry too much about it, but maybe you can apply the text overflow property only when its unfocused? https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

It sounds like the padding-right fix would work for the focused state.

**Comment by inclinedmind** [comment]
> I just checked and the overflowing can be fixed by adding a padding-right to the token input, as for the unfocused state, maybe that can be accomplished with the number formatting in the input?

Cool I'll give that a try, for some reason I wasn't having the overflow issue on my end

**Comment by inclinedmind** [comment]
noticed weird behavior if you try to input a number with more than 18 decimal places that rounds up to a higher number, will look into it

**Comment by inclinedmind** [comment]
I added a padding right to the token input as @iceanddust suggested. I was having trouble getting it to show ellipsis when the input is unfocused, but don't think it's a big deal.

I also prevented exponential notation, because before if you inputted something like `1e1` it would cause the app to crash, and accounted for commas instead of decimals in case we allow for international input formats.

**Review by generatorpoint — APPROVED** [review]
nice, looks way better

**Review by iceanddust — APPROVED** [review]
Looking good, lgtm!

**Pull request merged**
