### PR TITLE
Ignore locale files and recreate them during build

### PR DESCRIPTION
**Pull request by codewiththeflowxyz**
- Add all locale files ~.po~, .d.ts, .ts to .gitignore
- Recreate these files during build

NOTE: This is still in progress, feel free to continue with this. At the moment the build seems to work well, not the gitignore part.

UPDATE:
After removing the po file from the gitignore and remove the lingui extraction from the build script, the  testing app seems to work as expected.
image

### CODE REVIEW

**Comment by generatorpoint** [comment]
@codewiththeflowxyz I tried deleting the */locales/* files to see if it would add them on the build and I don't think it worked. If you need to, you can revert my commit.

**Comment by codewiththeflowxyz** [comment]
@generatorpoint I had to revert your commit but just because I needed to remove the .po files from the .gitignore.

**Review by bitsforpeace — APPROVED** [review]
Tested locally and it seems to work as expected

**Review by generatorpoint — APPROVED** [review]
awesome, works great!

**Pull request merged**
